### ISSUE TITLE
[ts] Property 'ref' does not exist on type 'RenderableProps<IProps>'

### ISSUE THREAD

**Issue by nhardy** [developit/preact#1076]
In the latest release 8.2.8 (which I understand is broken at this time), it seems like some typings are also broken.

When using refs in JSX, TypeScript complains with `[ts] Property 'ref' does not exist on type 'RenderableProps<IProps>'.`

E.g.
`<MyComponent ref={(ref: MyComponent) => (this.myComponent = ref)} />`

**Comment by marvinhagemeister** [comment]
Related: https://github.com/developit/preact/pull/1051

**Comment by marvinhagemeister** [comment]
Fixed by #1051

**Comment by nhardy** [comment]
@aaronjensen @marvinhagemeister: I'm still seeing the issue for `key` on a `FunctionalComponent`.

**Comment by marvinhagemeister** [comment]
@nhardy works fine for me with preact `8.2.9`. Can you post an example of your code?
