### ISSUE TITLE
[Bug] fail to render DOM correctly for component with key

### ISSUE THREAD

**Issue by foray1010** [developit/preact#56]
1. Render [VNode 1, VNode 2, VNode 3]
2. Update props and render [VNode 1, VNode 2, VNode 4]
3. Result in DOM [VNode 4] only

All VNodes have unique key
Remove key will work

Real life example: https://github.com/foray1010/Popup-my-Bookmarks/tree/preact
1. install the extension (npm install, npm install -g gulp, gulp dev, load __dev in chrome extension manager)
2. Open one folder in the root (let call it folder X)
3. Open a folder inside that folder X
4. Open another folder inside folder X
5. That "another folder" will be the only folder on the right, search field and the root folder will be removed

**Comment by foray1010** [comment]
There is another problem, but I am not sure about the cause and whether it is a bug
1. Render [VNode 1, VNode2]
2. Update props and render [VNode 1]
3. `render` of VNode2 will run

**Comment by developit** [comment]
@foray1010 is this happening on preact `3.4.0`?

**Comment by foray1010** [comment]
Yes, I am in 3.4.0

**Comment by developit** [comment]
Regarding your second issue, that's just how react/preact works.  If you are building components that are deterministic in their behaviour when re-rendered for the same props, I would suggest using a `shouldComponentUpdate` hook or `@pure` decorator:

```
class Foo extends Component {
  shouldComponentUpdate(props) {
    for (let i in props) if (props[i]!==this.props[i]) return true;
    return false;
  }
}
```

or the decorator:

```
// only re-render when props *change*:
@pure
class Foo extends Component {
  render() {  }
}


// here's an example implementation of that decorator:
function pure(ref) {
  ref.prototype.shouldComponentUpdate = function(props) {
    for (let i in props) if (props[i]!==this.props[i]) return true;
    return false;
  };
}
```

**Comment by foray1010** [comment]
I think my case is a bit different:
I have a state call `a` which is an array `[{text: '1'}, {text: '2'}]`

inside component `b`, I render an array of component `c` depends on state `a`
```js
const b = (props) => {
  // a is connected by redux
  let items = props.a.map((value, index) => <c index={index} />)

  return <div>{items}</div>
}

const c = (props) => (
  <div>{props.a[props.index].text}</div>
)
```

So, after I set `state.a` to [1] only, the `c` that was related to value `{text: '2'}` will fail to render because `props.a[props.index]` is undefined

I thought when rerender, preact should know that in `b`, I don't have `c` with `{text: '2'}` anymore, so why need to run `render` again?

**Comment by developit** [comment]
@foray1010 In your example, you're not passing the `a` prop to `<C>`.

**Comment by foray1010** [comment]
@developit thanks for the example! I may not be so clear, I should said that `a` is connected to all components by redux

Maybe it only happen when use with redux, I will generate an example to u tmr

**Comment by developit** [comment]
Alright, let me know.  It seems like the issue would be that the child component (`C`) is being re-rendered prior to the parent, so the parent has not yet removed it.

**Comment by foray1010** [comment]
I try to minimize the case, here it is: https://github.com/foray1010/test-preact

Main logic is in here: https://github.com/foray1010/test-preact/blob/master/js/containers/App.jsx

As I don't know how to use jsfiddle.net, please git clone it and
1. npm install
2. npm install gulp
3. gulp dev
4. run __dev/test.html

**Comment by developit** [comment]
Thanks for the awesome example, looking into this now.

**Comment by developit** [comment]
Fixed on master, releasing as `4.0` shortly.

**Comment by foray1010** [comment]
`4.0` doesn't fix the example: https://github.com/foray1010/test-preact
I still get `Uncaught TypeError: Cannot read property 'text' of undefined`

**Comment by developit** [comment]
The issue is that you're mapping parent state to the same prop.  Redux is triggering a re-render of your child component (`<Item>`), but only after the props have already triggered a re-render.

Can you try setting `syncComponentUpdates=false`?  Or I can.

```
import { options } from 'preact';

options.syncComponentUpdates = false;
```

I'm curious if it would fix the issue.

**Comment by foray1010** [comment]
no it doesn't fix the issue

**Comment by foray1010** [comment]
The issue in comment #1 is fixed by updating preact-compat from 0.7.1 to 1.6.0

**Comment by developit** [comment]
Sweet! The other issue still happens though?

**Comment by foray1010** [comment]
yes, I hv just updated https://github.com/foray1010/test-preact
Issue still happen no matter options.syncComponentUpdates is true or false
